services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "${PORT:-3000}:3000"
    environment:
      PORT: 3000

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
